### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [RaquelHdz/Proyecto_Final_Bioinf2017-II#1]
Ok, pero sólo especifica de cuántas poblaciones estamos hablando y recuerda que aunque trabajes con datos no genómicos será necesario utilizar herramientas de línea de comando o R

**Comment by AzaleaGuerra** [comment]
Mismo comentario que Alicia. Además, ¿qué especie de cangrejo? Recuerda que el preprocesamiento de ese tipo de datos es diferente al que se hace con datos de NGS.

**Comment by RaquelHdz** [comment]
ok, explico esto en el segundo avance
